-- Schema v2 para veículo (CAR): atributos detalhados do anúncio.
-- Mantém todos os campos da v1 (mileage_km, year_model, year_build, fuel, transmission, etc.)
-- e adiciona ~50 novos campos (motor, mecânica, dimensões, carroceria, segurança, conforto).
-- O DynamicAttributeValidationService já pega a versão mais alta quando há conflito,
-- portanto produtos existentes continuam validados pela v1 até serem republicados.
INSERT INTO attribute_schemas (country_code, realm, category_path, entity_type, version, schema_definition)
VALUES (
    'BR',
    'CAR',
    'carros',
    'product',
    2,
    '{
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "mileage_km":      { "type": "integer", "minimum": 0, "maximum": 2000000 },
        "year_model":      { "type": "integer", "minimum": 1950, "maximum": 2100 },
        "year_build":      { "type": "integer", "minimum": 1950, "maximum": 2100 },
        "fuel":            { "type": "string", "enum": ["Flex", "Gasolina", "Álcool", "Diesel", "GNV", "Elétrico", "Híbrido", "Híbrido plug-in"] },
        "transmission":    { "type": "string", "enum": ["Manual", "Automático", "Automatizado", "CVT", "Automática sequencial", "Automatizada de embreagem simples", "Automatizada de embreagem dupla"] },
        "color":           { "type": "string", "maxLength": 60 },
        "doors":           { "type": "integer", "minimum": 2, "maximum": 5 },
        "engine":          { "type": "string", "maxLength": 40 },
        "vin":             { "type": "string", "minLength": 17, "maxLength": 17 },
        "license_plate":   { "type": "string", "pattern": "^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$" },
        "previous_owners": { "type": "integer", "minimum": 0, "maximum": 50 },
        "warranty_months": { "type": "integer", "minimum": 0, "maximum": 120 },
        "factory_warranty":    { "type": "boolean" },
        "mechanical_warranty": { "type": "boolean" },
        "inspection_done":     { "type": "boolean" },

        "cylinders":            { "type": "integer", "enum": [1, 2, 3, 4, 5, 6, 8, 10, 12, 16] },
        "cylinder_layout":      { "type": "string",  "enum": ["Linha", "V", "W", "Boxer", "Radial", "Plano", "Outro"] },
        "engine_displacement_l":{ "type": "number",  "minimum": 0, "maximum": 12 },
        "power_hp":             { "type": "integer", "minimum": 0, "maximum": 2000 },
        "torque_nm":            { "type": "integer", "minimum": 0, "maximum": 5000 },
        "valves_per_cylinder":  { "type": "integer", "minimum": 1, "maximum": 8 },
        "fuel_supply":          { "type": "string",  "enum": ["Injeção eletrônica", "Carburador", "Injeção direta", "Outro"] },
        "fuel_tank_l":          { "type": "number",  "minimum": 0, "maximum": 300 },
        "consumption_city":     { "type": "number",  "minimum": 0, "maximum": 100 },
        "consumption_highway":  { "type": "number",  "minimum": 0, "maximum": 100 },
        "top_speed_kmh":        { "type": "integer", "minimum": 0, "maximum": 500 },
        "zero_to_hundred_s":    { "type": "number",  "minimum": 0, "maximum": 60 },

        "length_mm":     { "type": "integer", "minimum": 0, "maximum": 20000 },
        "width_mm":      { "type": "integer", "minimum": 0, "maximum": 5000 },
        "height_mm":     { "type": "integer", "minimum": 0, "maximum": 5000 },
        "wheelbase_mm":  { "type": "integer", "minimum": 0, "maximum": 10000 },
        "weight_kg":     { "type": "integer", "minimum": 0, "maximum": 100000 },
        "trunk_l":       { "type": "integer", "minimum": 0, "maximum": 5000 },
        "seats":         { "type": "integer", "minimum": 1, "maximum": 50 },
        "body_type":     { "type": "string",  "enum": ["Sedan", "Hatch", "SUV", "Cupê", "Perua", "Pickup", "Van", "Furgão", "Off-road"] },

        "drivetrain":          { "type": "string",  "enum": ["Dianteira", "Traseira", "4x4", "AWD"] },
        "steering":            { "type": "string",  "enum": ["Mecânica", "Hidráulica", "Elétrica", "Eletro-hidráulica"] },
        "transmission_detail": { "type": "string",  "enum": ["Manual", "Automática", "Automática sequencial", "CVT", "Automatizada", "Automatizada de embreagem simples", "Automatizada de embreagem dupla"] },
        "gears":               { "type": "integer", "minimum": 1, "maximum": 10 },
        "armored":             { "type": "boolean" },
        "armored_level":       { "type": "string",  "enum": ["III-A", "III", "II"] },

        "condition":        { "type": "string",  "enum": ["Novo", "Usado", "Seminovo"] },
        "accept_trade":     { "type": "boolean" },
        "financed":         { "type": "boolean" },
        "ipva_paid":        { "type": "boolean" },
        "licensing_year":   { "type": "integer", "minimum": 2000, "maximum": 2100 },
        "last_plate_digit": { "type": "integer", "minimum": 0, "maximum": 9 },

        "abs_brakes":           { "type": "boolean" },
        "ebd":                  { "type": "boolean" },
        "esp":                  { "type": "boolean" },
        "traction_control":     { "type": "boolean" },
        "asr":                  { "type": "boolean" },
        "hill_holder":          { "type": "boolean" },
        "airbag_driver":        { "type": "boolean" },
        "airbag_passenger":     { "type": "boolean" },
        "airbag_side":          { "type": "boolean" },
        "airbag_knee":          { "type": "boolean" },
        "airbag_curtain":       { "type": "boolean" },
        "isofix":               { "type": "boolean" },
        "blind_spot_monitor":   { "type": "boolean" },
        "lane_departure":       { "type": "boolean" },

        "front_camera":         { "type": "boolean" },
        "rear_camera":          { "type": "boolean" },
        "parking_sensor_front": { "type": "boolean" },
        "parking_sensor_rear":  { "type": "boolean" },

        "cruise_control":       { "type": "boolean" },
        "adaptive_cruise":      { "type": "boolean" },
        "speed_limiter":        { "type": "boolean" },
        "rain_sensor":          { "type": "boolean" },
        "headlight_auto":       { "type": "boolean" },
        "fog_lights_front":     { "type": "boolean" },
        "fog_lights_rear":      { "type": "boolean" },
        "led_headlights":       { "type": "boolean" },
        "xenon_headlights":     { "type": "boolean" },
        "leather_seats":        { "type": "boolean" },
        "heated_seats":         { "type": "boolean" },
        "electric_seats":       { "type": "boolean" },
        "sunroof":              { "type": "boolean" },
        "panoramic_roof":       { "type": "boolean" },
        "tinted_windows":       { "type": "boolean" },
        "ac":                   { "type": "boolean" },
        "digital_ac":           { "type": "boolean" },
        "climate_control":      { "type": "boolean" },
        "defrost_rear":         { "type": "boolean" },
        "rear_wiper":           { "type": "boolean" },
        "roof_rack":            { "type": "boolean" },
        "spare_tire_holder":    { "type": "boolean" },
        "alarm":                { "type": "boolean" },
        "central_lock":         { "type": "boolean" },
        "keyless_entry":        { "type": "boolean" },
        "keyless_start":        { "type": "boolean" },
        "power_windows":        { "type": "boolean" },
        "auto_windows":         { "type": "boolean" },
        "electric_mirrors":     { "type": "boolean" },
        "auto_folding_mirrors": { "type": "boolean" },
        "heated_mirrors":       { "type": "boolean" },
        "power_tailgate":       { "type": "boolean" },
        "trip_computer":        { "type": "boolean" },
        "lights_on_warning":    { "type": "boolean" },
        "cup_holder":           { "type": "boolean" },
        "steering_controls":    { "type": "boolean" },

        "am_fm":            { "type": "boolean" },
        "bluetooth":        { "type": "boolean" },
        "cd_player":        { "type": "boolean" },
        "dvd_player":       { "type": "boolean" },
        "mp3_player":       { "type": "boolean" },
        "aux_input":        { "type": "boolean" },
        "usb_input":        { "type": "boolean" },
        "android_auto":     { "type": "boolean" },
        "apple_carplay":    { "type": "boolean" },
        "gps":              { "type": "boolean" },
        "wifi":             { "type": "boolean" },

        "internal_trunk_release": { "type": "boolean" }
      }
    }'::jsonb
)
ON CONFLICT (country_code, entity_type, realm, category_path, version) DO NOTHING;
