CREATE TABLE IF NOT EXISTS public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid uuid NOT NULL,
  username varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  phone varchar(255) NOT NULL,
  password varchar(255),
  attributes jsonb,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz,
  deleted_at timestamptz
);