CREATE TABLE IF NOT EXISTS public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  username varchar(255) NOT NULL UNIQUE,
  email varchar(255) NOT NULL UNIQUE,
  phone varchar(255) NOT NULL UNIQUE,
  password varchar(255),
  attributes jsonb,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz,
  deleted_at timestamptz
);