-- Seed de marcas de veículos (dados FIPE)
-- vehicle_type: CAR, MOTORCYCLE, TRUCK, NAUTICAL, BUS

-- ── CAR (Carros) ──────────────────────────────────────────────────────────────
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 1, 'CHEVROLET', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 2, 'VOLKSWAGEN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 3, 'FIAT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 4, 'MERCEDES-BENZ', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 5, 'CITROEN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 6, 'CHANA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 7, 'HONDA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 8, 'SUBARU', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 10, 'FERRARI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 11, 'BUGATTI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 12, 'LAMBORGHINI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 13, 'FORD', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 14, 'HYUNDAI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 15, 'JAC', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 16, 'KIA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 17, 'GURGEL', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 18, 'DODGE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 19, 'CHRYSLER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 20, 'BENTLEY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 21, 'SSANGYONG', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 22, 'PEUGEOT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 23, 'TOYOTA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 24, 'RENAULT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 25, 'ACURA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 26, 'ADAMO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 27, 'AGRALE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 28, 'ALFA ROMEO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 29, 'AMERICAR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 31, 'ASTON MARTIN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 32, 'AUDI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 34, 'BEACH', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 35, 'BIANCO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 36, 'BMW', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 37, 'BORGWARD', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 38, 'BRILLIANCE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 41, 'BUICK', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 42, 'CBT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 43, 'NISSAN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 44, 'CHAMONIX', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 46, 'CHEDA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 47, 'CHERY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 48, 'CORD', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 49, 'COYOTE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 50, 'CROSS LANDER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 51, 'DAEWOO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 52, 'DAIHATSU', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 53, 'VOLVO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 54, 'DE SOTO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 55, 'DETOMAZO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 56, 'DELOREAN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 57, 'DKW-VEMAG', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 59, 'SUZUKI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 60, 'EAGLE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 61, 'EFFA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 63, 'ENGESA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 64, 'ENVEMO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 65, 'FARUS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 66, 'FERCAR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 68, 'FNM', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 69, 'PONTIAC', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 70, 'PORSCHE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 72, 'GEO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 74, 'GRANCAR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 75, 'GREAT WALL', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 76, 'HAFEI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 78, 'HOFSTETTER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 79, 'HUDSON', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 80, 'HUMMER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 82, 'INFINITI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 83, 'INTERNATIONAL', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 86, 'JAGUAR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 87, 'JEEP', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 88, 'JINBEI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 89, 'JPX', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 90, 'KAISER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 91, 'KOENIGSEGG', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 92, 'LAUTOMOBILE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 93, 'LAUTOCRAFT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 94, 'LADA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 95, 'LANCIA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 96, 'LAND ROVER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 97, 'LEXUS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 98, 'LIFAN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 99, 'LINCOLN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 100, 'LOBINI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 101, 'LOTUS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 102, 'MAHINDRA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 104, 'MASERATI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 106, 'MATRA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 107, 'MAYBACH', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 108, 'MAZDA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 109, 'MENON', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 110, 'MERCURY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 111, 'MITSUBISHI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 112, 'MG', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 113, 'MINI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 114, 'MIURA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 115, 'MORRIS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 116, 'MP LAFER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 117, 'MPLM', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 118, 'NEWTRACK', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 119, 'NISSIN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 120, 'OLDSMOBILE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 121, 'PAG', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 122, 'PAGANI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 123, 'PLYMOUTH', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 124, 'PUMA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 125, 'RENO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 126, 'REVA-I', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 127, 'ROLLS-ROYCE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 129, 'ROMI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 130, 'SEAT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 131, 'UTILITARIOS AGRICOLAS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 132, 'SHINERAY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 137, 'SAAB', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 139, 'SHORT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 141, 'SIMCA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 142, 'SMART', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 143, 'SPYKER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 144, 'STANDARD', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 145, 'STUDEBAKER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 146, 'TAC', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 147, 'TANGER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 148, 'TRIUMPH', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 149, 'TROLLER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 150, 'UNIMOG', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 154, 'WIESMANN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 155, 'CADILLAC', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 156, 'AM GEN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 157, 'BUGGY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 158, 'WILLYS OVERLAND', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 161, 'KASEA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 162, 'SATURN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 163, 'SWELL MINI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 175, 'SKODA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 239, 'KARMANN GHIA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 254, 'KART', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 258, 'HANOMAG', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 261, 'OUTROS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 265, 'HILLMAN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 288, 'HRG', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 295, 'GAIOLA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 338, 'TATA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 341, 'DITALLY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 345, 'RELY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 346, 'MCLAREN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('CAR', 534, 'GEELY', NOW(), NOW());

-- ── MOTORCYCLE (Motos) ────────────────────────────────────────────────────────
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 7, 'HONDA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 27, 'AGRALE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 36, 'BMW', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 59, 'SUZUKI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 98, 'LIFAN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 102, 'MAHINDRA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 132, 'SHINERAY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 133, 'KASINSKI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 135, 'YAMAHA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 136, 'GARINNI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 140, 'SUNDOWN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 170, 'KAWASAKI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 171, 'POLARIS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 176, 'ADLY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 177, 'AMAZONAS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 178, 'APRILIA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 179, 'ATALA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 180, 'BAJAJ', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 181, 'BENELLI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 182, 'BETA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 183, 'BIMOTA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 184, 'BRANDY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 185, 'BRAVA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 186, 'BRP', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 187, 'BUELL', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 188, 'BUENO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 190, 'CAGIVA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 191, 'MOBILETE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 192, 'DAELIM', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 193, 'DAFRA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 194, 'DAYANG', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 195, 'DAYUN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 196, 'DERBI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 197, 'DUCATI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 198, 'EMME', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 200, 'FYM', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 201, 'GAS GAS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 202, 'GREEN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 203, 'HAOBAO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 204, 'HARLEY-DAVIDSON', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 205, 'HARTFORD', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 206, 'HERO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 207, 'HUSABERG', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 208, 'HUSQVARNA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 209, 'IROS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 210, 'JIAPENG VOLCANO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 211, 'JOHNNYPAG', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 212, 'JONNY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 213, 'KAHENA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 214, 'KIMCO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 215, 'LAQUILA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 216, 'LANDUM', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 217, 'LAVRALE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 218, 'LERIVO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 219, 'LON-V', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 220, 'TRICICLO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 221, 'MALAGUTI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 222, 'MIZA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 223, 'MOTO GUZZI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 224, 'MRX', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 225, 'MV AUGUSTA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 226, 'MVK', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 227, 'ORCA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 228, 'PEGASSI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 229, 'PIAGGIO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 230, 'REGAL RAPTOR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 231, 'SANYANG', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 232, 'SIAMOTO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 233, 'TARGOS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 234, 'TRAXX', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 235, 'VENTO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 236, 'WUYANG', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 245, 'GARRA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 246, 'X MOTOS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 248, 'TRICKER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 253, 'LAMBRETA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 261, 'OUTROS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 269, 'SCOOTER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 281, 'ZONGSHEN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 282, 'BIRELLI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 294, 'WALK MACHINE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 297, 'FBM', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 299, 'ARIEL', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 340, 'DUCAR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 341, 'DITALLY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 342, 'MARVA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 343, 'WOLVER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 344, 'KTM', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 347, 'LEOPARD', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 348, 'JAWA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 349, 'BULL', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 358, 'CAN-AM', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 359, 'ACELLERA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 483, 'VICTORY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 484, 'INDIAN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 532, 'BRAVAX', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('MOTORCYCLE', 533, 'GARELLI', NOW(), NOW());

-- ── TRUCK (Caminhões) ─────────────────────────────────────────────────────────
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 1, 'CHEVROLET', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 2, 'VOLKSWAGEN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 3, 'FIAT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 4, 'MERCEDES-BENZ', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 6, 'CHANA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 13, 'FORD', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 14, 'HYUNDAI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 16, 'KIA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 23, 'TOYOTA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 24, 'RENAULT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 27, 'AGRALE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 53, 'VOLVO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 84, 'ISUZU', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 85, 'IVECO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 131, 'UTILITARIOS AGRICOLAS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 164, 'TRAILER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 167, 'RANDON', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 242, 'SCANIA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 261, 'OUTROS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 263, 'ONIBUS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 266, 'UTILITARIOS PESADOS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 270, 'MOTOR-HOME', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 274, 'MAN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 275, 'NAVISTAR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 277, 'SINOTRUK', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 284, 'SCHIFFER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 285, 'GUERRA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('TRUCK', 292, 'MICHIGAN', NOW(), NOW());

-- ── NAUTICAL (Náuticos) ───────────────────────────────────────────────────────
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 4, 'MERCEDES-BENZ', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 7, 'HONDA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 53, 'VOLVO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 59, 'SUZUKI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 135, 'YAMAHA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 170, 'KAWASAKI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 261, 'OUTROS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 351, 'ECOMARINER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 352, 'VENTURA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 353, 'EVINRUDE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 354, 'FIBRAFORT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 355, 'SCHAEFER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 356, 'CARBRASMAR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 357, 'SEA-DOO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 359, 'ACELLERA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 360, 'INTERMARINE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 361, 'MAGNA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 362, 'AZIMUT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 363, 'CIMITARRA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 364, 'FERRETTI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 365, 'BENETEAU', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 366, 'MONTE CARLO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 367, 'LAGOON', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 368, 'FISHING', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 369, 'REAL POWER BOATS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 370, 'MAGNUM', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 371, 'AGUZ', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 372, 'MILLENIUM', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 373, 'ALTERNATIVA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 374, 'BAYLINER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 375, 'AQUA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 376, 'MOONEN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 377, 'AQUATERRA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 378, 'ARMADA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 379, 'ARTHMARINE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 380, 'AXTOR MARINE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 381, 'AVALON', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 382, 'BAIA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 383, 'BAJA MARINE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 384, 'BENETTI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 385, 'BILGIN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 386, 'BMYD', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 387, 'BRASBOATS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 388, 'BRAVA YACHTS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 389, 'BRAZILIAN BOAT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 390, 'CANTIERI DI PISA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 391, 'CAPRICE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 392, 'CENTURY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 393, 'CHRIS CRAFT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 394, 'COLUNNA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 395, 'CORAL', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 396, 'CRANCHI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 397, 'CROWNLINE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 398, 'LUNA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 400, 'MERCURY MARINE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 401, 'MAGIS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 402, 'TOP BOATS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 403, 'DIAMAR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 404, 'COBRA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 405, 'ARBOAT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 406, 'ALBATROZ', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 407, 'B3', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 408, 'BATE VENTO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 409, 'BERTRAM', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 410, 'BRAMADOR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 411, 'BRUDDEN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 412, 'CARABELLI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 413, 'DONZI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 414, 'DELTA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 415, 'LEVEFORT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 416, 'NAUTIQUE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 417, 'EDGEWATER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 418, 'FORMULA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 419, 'HARRIS FLOTEBOTE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 420, 'MASTERCRAFT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 421, 'DOLPHIN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 422, 'DREAMBOATS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 423, 'ESQUIMAR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 424, 'EUROBOATS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 425, 'EVOLUTION', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 426, 'EVOLVE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 427, 'FAIRLINE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 429, 'MIDNIGHT EXPRESS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 430, 'STATEMENT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 431, 'MTI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 432, 'LUND', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 433, 'ALUMACRAFT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 434, 'LOWE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 435, 'FLASH', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 436, 'FLEXBOAT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 437, 'FLORIDA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 438, 'YANMAR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 439, 'FLYBOAT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 440, 'FORCE ONE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 441, 'FOUNTAINE PAJOT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 442, 'FOUR WINNS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 443, 'FS YACHTS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 444, 'FUTURA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 445, 'GAMPER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 446, 'GENESIS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 447, 'GIANETTI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 448, 'HD MARINE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 449, 'HOLOS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 450, 'BELASSI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 451, 'IMPERIO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 452, 'INACE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 453, 'INTECH', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 454, 'JEANNEAU', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 455, 'PRESTIGE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 456, 'PALMER JOHNSON', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 457, 'KALMAR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 458, 'LENZI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 459, 'LANCER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 460, 'LAZZARA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 461, 'TRIUMPH BOATS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 462, 'LOTHAR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 463, 'MAESTRALE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 464, 'MALIBU', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 465, 'MARES', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 466, 'MARINER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 467, 'MASTERBOAT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 468, 'MAXIMA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 469, 'MCP YACHTS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 470, 'METALGLASS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 471, 'MINASFORTE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 472, 'MJ YACHTS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 473, 'MOCHI CRAFT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 474, 'MONTEREY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 475, 'MOOMBA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 476, 'MWM', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 477, 'NAUTIFLEX', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 478, 'PAPA E PALAZZINI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 479, 'PERI YACHTS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 480, 'PERSHING', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 481, 'PHANTOM', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 482, 'PHOENIX', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 485, 'POLARIS BOATS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 486, 'PRINCESS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 487, 'PROMAR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 488, 'PSARI', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 489, 'RANGER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 490, 'RECON', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 491, 'REGAL', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 492, 'RIOSTAR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 493, 'RIVA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 494, 'RIVAL', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 495, 'ROYAL MARINER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 496, 'RUNNER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 497, 'SAGA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 498, 'SAIL MASTER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 499, 'SAPPHIRE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 500, 'SEA CREST', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 501, 'SEA RAY', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 502, 'SEA HAWK', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 503, 'SEGUE YACHTS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 504, 'SESSA MARINE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 505, 'SILVERTON', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 506, 'SKIPPER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 507, 'STERLING', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 508, 'STRIDER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 509, 'SUNFLASH', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 510, 'SUNLINE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 511, 'SUNSEEKER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 512, 'SUPERBOATS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 513, 'SUPRA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 514, 'TECNOBOATS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 515, 'TECHNOMARINE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 516, 'TEMPEST', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 517, 'TOHATSU', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 518, 'TRITON', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 519, 'VEGA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 520, 'VICTORY YACHTS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 521, 'WALGLASS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 522, 'WELLCRAFT', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 523, 'YACXO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 524, 'ZEFIR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 525, 'ZODIAC', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 526, 'ZONDA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 527, 'FLIPPER', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 528, 'GALEON', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 529, 'HEESEN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 530, 'KRAUSE', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('NAUTICAL', 531, 'SUNREEF', NOW(), NOW());

-- ── BUS (Ônibus) ──────────────────────────────────────────────────────────────
-- Marcas de ônibus não presentes nos CSVs FIPE, adicionadas manualmente
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('BUS', 9001, 'MARCOPOLO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('BUS', 9002, 'CAIO', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('BUS', 9003, 'BUSSCAR', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('BUS', 9004, 'VOLVO BUSES', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('BUS', 9005, 'MERCEDES-BENZ', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('BUS', 9006, 'SCANIA', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('BUS', 9007, 'IRISBUS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('BUS', 9008, 'IVECO BUS', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('BUS', 9009, 'NEOPLAN', NOW(), NOW());
INSERT INTO vehicle_brands (vehicle_type, fipe_id, name, created_at, updated_at) VALUES ('BUS', 9010, 'DAF BUS', NOW(), NOW());

